name: Run Our own action
on:
  pull_request:
    branch:
      - master

jobs:
  justRun:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: see output of custom action
        uses: ./
